_people2_.txt
https://github.com/oss2025hnu/reposcore-py/issues/249
위의 이슈를 해결하기위해
석원담 정보가 _people2_.txt에 추가
=> 석원담 정보가 _people2_.txt에 추가

README.md, reposcore/__main__.py, reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/275 --output 옵션의 동작이 실제와 다름 이슈에 대한 PR입니다.
** Version (commit id) **
ea6255f843c8615af12cfc05909d3cc87cb257d5
--output 옵션으로 명시된 리렉토리 하위에 table.csv, chart.png 파일이 생성 되도록 수정했습니다.
--output 옵션 미지정시 기본값인 results 디렉토리 하위에 생성됩니다.
=> [FIX] --output 옵션이 출력 디렉토리에 제대로 반영되지 않던 문제 수정

tests/test_analyzer.py, tests/test_main.py
https://github.com/oss2025hnu/reposcore-py/issues/299 calculate_scores 함수에 대한 테스트 코드 작성 제안에 대한 PR입니다.
** Version (commit id) **
1fa2cecea05eabffd2059189e1c1468f764e1fbd
10개의 예제 테스트를 추가하였고, 테스트 실행시 table.csv, chart.png 모두 생성되도록 변경했습니다.
=> [TEST] calculate_scores 함수에 대한 예제 테스트 추가

.gitignore, reposcore/__main__.py
#306  GitHub 데이터 수집 결과 캐시 기능 추가
**Version (commit id)**  
8e24367bc5b6a767816cddc10ff827f7f2a2cd15
**수정 사항**  
- `--use-cache` 옵션을 통해 participants 데이터를 캐시(`cache.json`)로 저장/불러오는 기능을 추가했습니다.
- 캐시가 존재하고 `--use-cache` 옵션이 주어졌을 경우, GitHub API 호출 없이 캐시 파일을 불러옵니다.
- 캐시 파일이 없거나 `--use-cache`가 없는 경우, 기존 방식대로 데이터를 수집하고 캐시에 저장합니다.
- 결과 파일(`table.csv`, `chart.png`)은 `.gitignore`에 의해 커밋되지 않도록 설정했습니다.
**Describe alternatives you've considered**  
- 매 실행 시마다 새롭게 데이터를 불러오는 방식은 비효율적이라 자동 캐시 방식으로 구현했습니다.
- 수동 지정 방식도 고려했지만, 현재는 자동 캐시가 더 직관적입니다.
**추가 설명**  
- 캐시 파일 이름은 `cache.json`이며, 저장 디렉토리는 `--output` 인자에 따라 결정됩니다.
=> 캐시 기능 추가 및 결과 파일 무시 처리

tests/test_main.py
#317 [FEAT] --repo 옵션에 대한 에지 케이스 처리 추가에 대한 PR입니다.
13b54253d70ca7c66a9caddf3ef03fc62bfe9daa
추가사항
`reposcore/__main__.py`의 `--repo` 옵션과 관련된 예외 상황에 대한 테스트를
`tests/test_main.py`에 추가했습니다.
다음과 같은 에지 케이스에 대해 테스트를 작성
- `--repo` 옵션 없이 실행한 경우  
- 잘못된 형식의 저장소를 입력한 경우  
- 존재하지 않는 GitHub 저장소를 입력한 경우
Test Result
`make test` 명령어를 통해 모든 테스트가 정상적으로 통과했음을 확인했습니다.
=> --repo 옵션에 대한 에지 케이스 처리 추가

README.md, reposcore/__main__.py, reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/290 해당 이슈에 대한 PR입니다.
e19389858589bd03ae04888d11b1529c5418a083
**수정사항**
기존 csv 파일을 생성하던`generate_table`함수를 유지한채, 기존에는 총점만 기록하였지만 현재는 각각의 점수와 총점을 기록하도록 변경하였습니다.
PrettyTable을 사용한 테이블을 출력하는 `generate_text` 함수를 구현하였습니다.
명령줄 인자의 --format이 'table', 'text', 'chart', 'all' 로 변경되었으며, 'table' 선택시 csv파일만을, 'text' 선택시 'csv' 파일과 'txt'파일을 생성합니다. 'all' 선택시 모든 파일을 생성합니다.
generate_table 함수와 generate_text가 각각의 점수를 기록하는 과정에서, 기존의 `scores`는 총점만을 가지고 있기 떄문에 변경이 필요하였습니다. 하지만 현재 generate_chart 에서 기존의 `scores`를 사용중이기 때문에 임시로 `scores_temp` 전역변수를 선언하였고, 각 부분의 점수와 총점을 담아 사용하였습니다.
이 부분은 추후 `scores` 가 `scores_temp` 의 값을 가지게 변경하고, 변경된  `scores` 에 알맞게 `generate_table` , `generate_text `  , `generate_chart` 를 수정하는 이슈를 생성하는게 좋을 것 같습니다.
=> [FEAT] generate_table 수정 및 generate_text 생성

reposcore/__main__.py, reposcore/analyzer.py
[FEAT] GitHub API 요청 시 비로그인 유저 rate limit 초과 문제 개선https://github.com/oss2025hnu/reposcore-py/issues/301 에 대한 PR입니다.
**Specify version (commit id)**
623ce447f12da6b4b409d11567d2da0fb7788ca9
**변경사항**
GitHub API 요청 시 인증을 통해 rate limit 문제를 해소할 수 있도록 하기 위해, CLI에서 GitHub Personal Access Token을 입력받을 수 있는 기능을 추가했습니다. 해당 토큰은 RepoAnalyzer에 전달되어 이후 API 요청 시 인증 헤더에 활용될 수 있도록 구조를 준비했습니다.
- -token CLI 인자 추가
- RepoAnalyzer 클래스에 -token 인자 및 필드 추가
- 향후 Github API 호출 시 인증 헤더에 사용할 준비를 마쳤습니다. (헤더 추가 및 구현까지는 제 능력 밖의 일이었습니다..)
=> GitHub API 요청 시 비로그인 유저 rate limit 초과 문제 개선 PR

reposcore/__main__.py
[#346](https://github.com/oss2025hnu/reposcore-py/issues/346)
GitHub token을 환경변수 혹은 표준 입력(stdin)을 통해 설정할 수 있도록 수정했습니다.
```--token``` 옵션이 없거나 비어 있으면 ```GITHUB_TOKEN``` 환경 변수에서 불러오고, 만약 ```-``` 라면 표준 입력에서 불러옵니다.
=> Add feature to retrieve token from env variable or stdin

reposcore/__main__.py, reposcore/analyzer.py, reposcore/utils/retry_request.py
#301 [FEAT] GitHub API 요청 시 비로그인 유저 rate limit 초과 문제 개선 
Specify version (commit id)  https://github.com/oss2025hnu/reposcore-py/commit/c2150811da229e82f92013d022ed4174a010affe
**변경사항**
- REST API에 대한 인증로직 추가
=>  [FEAT] GitHub API 요청 시 비로그인 유저 rate limit 초과 문제 개선

scripts/generate_readme.py
https://github.com/oss2025hnu/reposcore-py/issues/331 make readme 실패에 대한 피드백이 안됨에 대한 PR입니다.
Specify version (commit id) 
9b95ad23d163106dbb6fad309748a2c77577a7af
- --help 명령어가 실패해도 `README.md` 를 생성하고 성공 메시지를 출력하는 문제가 있었습니다.
이제는 명령어 실패 시 에러 메시지를 출력하고 `README.md` 파일을 갱신하지 않습니다.
=> [FIX] make readme 실패에 대한 오류 메시지 추가

README.md, template_README.md
python -m reposcore ... 최상위 디렉토리에서 실행하라는 내용 README에 추가 [oss2025hnu#310](https://github.com/oss2025hnu/reposcore-py/issues/310) 에 대한 PR입니다.
a5b5853
변경사항
* README.md의 ## Usage 섹션에 python -m reposcore [OPTIONS] 형태의 CLI 명령어 예시 추가
* python -m reposcore -h 결과를 반영한 명령어 옵션 설명 템플릿 추가 ({{ usage }} 포함)
* 저장소 최상위 경로에서 명령어를 실행해야 한다는 안내 문구 삽입
Describe alternatives you've considered
* README.md의 사용법을 단순히 한 줄로 요약하는 방식도 고려했으나,
사용자 입장에서 실제 명령어 실행 예시(python -m reposcore [OPTIONS])와 함께 -h 결과를 함께 보여주는 것이 더 직관적이라 판단했습니다.
* GitHub Actions 또는 위키 문서로 따로 분리하여 설명하는 방법도 있었지만,
README.md가 가장 접근성이 높아 이곳에 포함하는 방향을 택했습니다.
=> python -m reposcore ... 최상위 디렉토리에서 실행하라는 내용 README에 추가 #310

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/381 해당 이슈에서 발생했던  retry_request 함수의 오류를 수정하였습니다.
Version (commit id)
1fb1cea7bad16a8b8682738e09aa8707e494fadb
**수정내용**
`retry_request` 함수의 인자 중 `session` 값이 제대로 전달되고 있지 않다는 것을 확인하였습니다. 
`self.SESSION = requests.Session()` 에서 선언되었던 `self.SESSION` 값을 사용해 올바른 인자를 넣어주었습니다.
=> [BUG] retry_request 함수의 오류 수정.

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/360 해당 이슈에서 발생했던  score formula 공식을 수정하였습니다.
Version (commit id)
7f0661c274e668a469cbd33c74c4d6812fb96cd8
수정내용
analyzer.py 에서 score formula 공식 중 pvaild 값 때문에 거의 대부분 학생들의 점수가 0으로 되어 있는 것을 확인하였습니다.
그래서 실습수업시간때 교수님께서 공개적으로 알려주신 공식을 이용하여 대부분 학생들이 0점이 나오지 않도록 수정했습니다.(명령어를 사용해봤는데 여전히 0점으로 나온 학생이 4명 나옵니다.)
=> 너무 많은 사람들의 점수가 0점으로 계산됨 을 수정함

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/385
GitHub API 남은 요청 횟수 확인 기능에 대한 pr입니다!
Specify version (commit id) 47014fe
826916aadded660ba2f4f6154da5030ac846a6c5
변경사항
1.새로운 --check-limit 옵션을 추가하여 사용자가 GitHub API의 현재 잔여 요청 수와 전체 한도를 확인할 수 있도록 했습니다.
(이 옵션이 활성화되면 저장소 인자(예: "owner/repo") 없이도 명령어를 실행할 수 있도록 했습니다,
단  --check-limit 옵션이 없는 경우에는 repository 인자가 필요하며 "API 요청 제한 정보를 가져오는데 실패했습니다"라는 오류가 뜨게 함)
2."사용자가 원할 때만 확인할 수 있도록 선택적 옵션으로 구현"을 위해 잔여횟수를 확안 한 후
reposcore 프로그램이 종료되어 명령 실행이 끝나고 터미널은 다시 커맨드 프롬프트 상태로 돌아도록 작성하였습니다
추가적인 이해를 위해 테스트사진 첨부
(위의 사진처럼 "python -m reposcore --check-limit"명령어 입력시 횟수 확인 가능)
=> GitHub API 남은 요청 횟수 확인 기능 #385

reposcore/__main__.py
[BUG] --format 옵션 설명에 잘못된 예시값에 대한 PR입니다. (https://github.com/oss2025hnu/reposcore-py/issues/383)
https://github.com/oss2025hnu/reposcore-py/commit/07b9d5753241b491c954abe27ea28ebc8660b8ad
변경사항
기존에 --format 옵션의 metavar가 [table|chart|both]로 되어 있었으나,
실제 허용되는 값은 "table", "chart", "all"입니다.
따라서 사용자 혼란을 줄이기 위해 metavar를 [table|chart|all]로 수정하였습니다.
=> [BUG] --format 옵션 설명에 잘못된 예시값 PR

.gitignore
[BUG] 실행 후 생성되는 table.txt파일 관리에 대한 PR입니. (https://github.com/oss2025hnu/reposcore-py/issues/401)
https://github.com/oss2025hnu/reposcore-py/commit/92b8527f9139a390b4ed6490b8672ec5caacc8ad
변경사항
table.txt는 실행 결과물로, PR에 포함될 필요가 없으므로 .gitignore에 추가하였습니다.
=> [BUG] 실행 후 생성되는 table.txt파일 관리에 대한 PR

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/393 csv 파일의 첫 번째 열에 name 컬럼 추가에 대한 PR입니다.
Specify version (commit id). 
92b8527f9139a390b4ed6490b8672ec5caacc8ad
- csv 파일의 첫 번째 열에 name 컬럼 추가되어 다음과 같이 출력됩니다.
- `name,feat/bug PR,document PR,feat/bug issue,document issue,total,rate`
=> [FEAT] csv 파일의 첫 번째 열에 name 컬럼 추가

reposcore/__main__.py, reposcore/utils/validators.py
https://github.com/oss2025hnu/reposcore-py/issues/295
해당건에 대한 pr입니다.
1번, 2번 : reposcore/utils/validators.py 파일을 새로 생성하여 해결하였습니다.
코드 설명 : 
- requests는 외부 라이브러리이기에 requests가 설치 되어있는지 확인하고 없다면 자동으로 설치하는 과정 추가
- 사용자가 입력한 저장소 이름이 owner/repo 형식을 따르는지 확인. 일치하지 않을 시 경고문 출력
- Github api를 통해 입력한 저장소가 실제하는지 확인, 맞지 않을시 경고문 출력
4번 : 이미 main.py에 호출객체, 예외처리, 실패대응까지 되어있습니다.
5번 역시 이미 main.py에 기능이 구현되어 있었음. 결과 출력이 영문인데다 불필요하게 긴 문장{output_dir} directory으로 작성된 듯 하여 {_path} 명령어로 가독성을 높였음.
6번 : main에 작성된 코드들이 이미 원활하게 흐름에 맞게 진행되고 있는것으로 보임. 별도의 작업이 필요 없다고 판단하였습니다.
=> [FEAT] CLI 진입점 및 인수 처리기능 추가/검증

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/433 에 대한 pr입니다.
--format 옵션을 복수 선택 가능하도록 개선했습니다.
ex) --format table chart 또는 --format text
"all"을 입력하면 기존처럼 세 가지 결과가 모두 출력됩니다.
내부에서는 set 자료형을 사용해 중복 제거 및 조건 검사를 개선했습니다.
도움말 메시지(--help)를 수정했습니다.
=> [FEAT] --format옵션 중복 선택이 가능하도록 개선 요청 

README.md, template_README.md
https://github.com/oss2025hnu/reposcore-py/issues/390
코드만 수정하고 readme에는 반영되지 않은것을 수정했습니다.
저는 $P_{\text{valid}} = P_{fb} + \min(P_d, 3 \times \max(P_{fb}, 1)) \quad$ 점수 인정 가능 PR 개수
(p_fb이 0일 경우에도 문서 PR 최대 3개까지 인정됩니다.)
두 줄만 수정했는데 readme.md의  다른 부분도 같이 수정된것으로 보아 이전 사용자가 template_README.md를 실행하고 이를 readme에 반영하지 않았던것 같습니다.
=> [DOC] 채점 공식 수정: 기능/버그 PR 0건 시 문서 PR 최대 3건 인정되도록 P_valid 수정 에대한 readme 수정

README.md, docs/korean-timezone-guide.md, template_README.md
https://github.com/oss2025hnu/reposcore-py/issues/441 에 대한PR
https://github.com/oss2025hnu/reposcore-py/commit/c7412e177aa74cd4d17857b8a3852dae665b99d8
**변경사항**
- `docs/korean-timezone-guide.md`  파일 추가
- `README.md` 하단에 링크 삽입
- Codespaces 및 GitHub Actions 환경에서 Asia/Seoul 시간대로 설정하는 방법 문서화
- export TZ=Asia/Seoul 사용법 포함
- CI 환경에서 시간대를 변경하는 YAML 설정 예시 포함
=> 한국 시간대 설정 가이드 추가

tests/test_main.py
https://github.com/oss2025hnu/reposcore-py/issues/430 test_main_without_repo_option 실패에 대한 PR입니다.
acdf195fcf42b3ca421ac89ce5c7f549cbba7732
- 에러 메시지가 `log(f"오류: 저장소 '{repo}'는 'owner/repo' 형식으로 입력해야 합니다. 예) 'oss2025hnu/reposcore-py'")`로 변경되어 `test_main_without_repo_option` 함수의 에러 메시지 포함 조건을 다음과 같이 변경했습니다.
- ` assert "'owner/repo' 형식으로" in result.stdout or "required" in result.stderr`
=> [FIX] test_main_without_repo_option 함수의 에러 메시지 포함 조견 변경

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/452
저장소 인자 처리 시 쉼표로 분리하는 로직이 여러 줄로 중복 작성되어 있어, 코드 가독성과 유지보수성이 떨어집니다. 
다음 한 줄의 List Comprehension으로 간결하게 수정하였습니다.
6cfe9344ed98a9bf2fa5b7e64e6fbf9b7558db3a
✅ 변경 전
```
final_repositories = []
for repo in repositories:
if "," in repo:
final_repositories.extend([r.strip() for r in repo.split(",") if r.strip()])
else:
final_repositories.append(repo)
final_repositories = list(dict.fromkeys(final_repositories))  # ❌ 이 줄 포함
```
✅변경 후(한 줄)
```
final_repositories = list(dict.fromkeys(
[r.strip() for repo in repositories for r in repo.split(",") if r.strip()]
))
```
=> [FEAT] Repository List Parsing 코드 리팩토링

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/457 에 대한 pr입니다.
a4584de1c2dc4ab9d1d5916f5017b9670ed90e1f
response.status_code == 401:를 추가하고 이와 같이 출력되도록 작성했습니다.
`❌ 인증 실패: 잘못된 GitHub 토큰입니다. 토큰 값을 확인해 주세요.`
=> [FEAT] 토큰이 잘못 입력 되었을 때 이를 알려주는 코드가 없습니다.에 대한 pr입니다.

README.md, docs/github_api_guide.md, template_README.md
https://github.com/oss2025hnu/reposcore-py/issues/484 [DOC] --check-limit 옵션 내용 github_api_guide.md로 이동 요청 에 대한 PR입니다.
5a73a55cc0b5e1ee44f78b2b28e1d4d1108e2aa1
**변경사항**
- template_README.md 파일에 있는 --check-limit 옵션 및 repository 인자에 관한 설명을 삭제하고,
해당 내용을 docs/github_api_guide.md 파일에 추가하여 GitHub API 관련 모든 정보가 한 곳에 집중되도록 수정
=> [DOC] --check-limit 옵션 내용 github_api_guide.md로 이동 요청 에 대한 PR

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/494
단순 출력하는 기능만 있는 그래프에, A~F등급의 라인을 그리는 기능을 추가했습니다. 
a5943ad0a45ec2b45ed950a772391cd3f0f0be0c
변경사항
y축에 평행하는 라인을 그려 그래프에 A~F 등급 라인 렌더링 기능 추가했습니다.
=> [FEAT] A~F등급을 그래프에 y축과 평행하기 그리는 기능이 추가되었으면합니다.

reposcore/__main__.py, reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/498 [BUG] 차트 이미지가 생성되지 않음 에 대한 PR입니다.
5f6cc480a3c1d09b17ac171eeaaabb9205259b13
**변경사항**
차트가 출력이 되지 않는 버그를 수정하였습니다.
=> [BUG] 차트 이미지가 생성되지 않음 에 대한 PR

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/510 [BUG] --help옵션 사용 시 usage의 출력이 상이함에 대한 PR입니다.
c172dcfa07910063ba24baa625967fa300bf823a
변경사항
parse_arguments 함수에서 --user-info 옵션을 usage에 추가했습니다.
=> [BUG] --help옵션 사용 시 usage의 출력이 상이함에 대한 PR입니다.

README.md, reposcore/__main__.py, template_README.md
https://github.com/oss2025hnu/reposcore-py/issues/518 에 대한 PR
https://github.com/oss2025hnu/reposcore-py/commit/8d1c9976338134e8b87b8092852147b191e49dcd
--grade 옵션이 argparse에 추가되었었지만, README에 반영되지 않아 make readme로 갱신하여 반영되도록 수정.
=> --grade 옵션 README에 사용법 반영

reposcore/analyzer.py
[#524](https://github.com/oss2025hnu/reposcore-py/issues/524)
- 각 참가자의 활동 내역을 집계하여
name,feat/bug PR,document PR,typo PR,feat/bug issue,document issue
형식의 CSV 파일(activity_count.csv) 을 추가로 생성합니다.
- 기존 점수 기반의 table.csv 와는 별도 파일로 저장됩니다.
- 파일 저장 위치는 동일하게 results/ 디렉토리입니다.
- 로그 출력 시, 두 파일의 생성 완료 메시지를 한 번에 출력하도록 개선하였습니다.
- .venv 환경에서 python main.py -r <user/repo> 실행
- 다음과 같은 로그 출력을 확인:
[📊 CSV 결과 저장 완료: results/table.csv]
[📄 활동 개수 CSV 저장 완료: results/activity_count.csv]
=> [FEAT] 참가자의 PR/이슈 개수 집계 CSV 파일 생성 기능 추가 (#524)

reposcore/__main__.py, reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/531
---
`results` 디렉토리 내 **출력 파일 구조와 이름을 통일**하고,  
**직관적이지 않은 파일명과 구조**를 리팩토링했습니다.
- `table.csv` → `score_participation.csv`로 명확하게 변경
- `table.txt` → `score_participation.txt`로 명확하게 변경
- `activity_count.csv` → `count_participation.csv`로 명확하게 변경
- 차트 이미지는 별도 디렉토리 없이 `results/chart_participation.png`로 통일
---
- 결과 파일명만 보고도 **각 파일의 용도 파악이 쉬워짐**
- `results` 디렉토리 내부가 **일관성 있고 직관적인 구조**로 정리됨
- 기여자 및 사용자들이 파일을 **빠르게 찾고 분석** 가능해짐
---
- 기존 파일 생성 로직은 그대로 유지하며, 파일명 및 위치만 수정하였습니다.
- 추후 추가되는 결과 파일도 이 naming rule을 따라가면 유지보수가 쉬워집니다.
=> [REFACT] result 디렉토리의 폴더 구조 및 파일명 통일

reposcore/__main__.py, reposcore/analyzer.py
#534 [FEAT] 로그 메시지에 로그 레벨을 함께 출력하는 기능 추가
https://github.com/oss2025hnu/reposcore-py/commit/8796e891a7b4e7a6ce04b997ebdfd3cc206e2005
**변경 내용**
로그 메시지에 로그 레벨을 함께 출력하는 기능 추가
=> [FEAT] 로그 메시지에 로그 레벨을 함께 출력하는 기능 추가에 대한 PR입니다.

reposcore/__main__.py
#531
결과물이 result폴더(디폴트값) 혹은 --output 인자를 통해 폴더를 지정했을 경우, chart.png 파일이 바깥으로 튀지 않도록 고쳤습니다.
=> [REFACTOR] --output 지정 디렉토리 path오류 리팩토링

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/544
generate_chart 메서드 내 폰트 설정 로직을 개선하여, 'NanumGothic' 폰트가 시스템에 설치되어 있지 않을 경우 'DejaVu Sans' 폰트를 대체로 사용하도록 수정했습니다.
이 변경으로 인해 'NanumGothic' 폰트가 없을 때 발생하는 경고 메시지가 더 이상 출력되지 않으며, 모든 환경에서 일관된 차트 렌더링이 가능합니다.
'NanumGothic' 폰트가 설치되어 있지 않은 시스템에서 차트를 생성할 때, 관련 경고 메시지가 과도하게 출력되는 문제가 있었습니다.
이 문제를 해결하기 위해 폰트가 설치되어 있는지 확인한 후, 없으면 대체 폰트를 사용하도록 로직을 개선했습니다.
'NanumGothic' 폰트가 설치된 환경과 설치되지 않은 환경에서 차트를 생성하여, 경고 메시지가 출력되지 않고 차트가 정상적으로 렌더링되는 것을 확인했습니다.
=> [BUG] NanumGothic 폰트가 없을 경우 로그가 과도하게 출력되는 문제 수정에 대한 PR

Makefile, docs/chart-font-guide.md, reposcore/analyzer.py
#512 
`Makefile`에 이슈에서 제시한 `install-fonts` 및 `update-fonts` target을 추가함.
`reposcore/analyzer.py`에 한글 폰트를 순차적으로 찾는 코드를 추가함.
`docs/chart-font-guide.md` 문서의 설명을 `make`를 사용하도록 변경함.
=> Makefile에 폰트 관련 target을 추가함

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/460
기존에 사용하던 plt.tight_layout(pad=2) 호출 시 warning이 발생하여
이를 해결하기 위해 constrained_layout=True 옵션을 사용해보았습니다.
하지만 이 경우에도 axes sizes collapsed to zero 경고가 추가로 발생하였습니다.
따라서 위 warning은 수평막대그래프의 구조적 한계로 보입니다. 특히 Y축에 69명의 참여자 이름을 전부 나열해야하는 상황에서는 matplotlib이 레이아웃 계산을 정상적으로 수행하지 것으로 판단됩니다.
따라서 기존에 자동으로 레이아웃을 적용하는 tight_layout 은 어차피 제 기능을 발휘하지 못하므로 제거하였습니다. 
여백을 수동으로 조정하는 방식으로 변경해주었습니다.
=> [BUG] 테스트시 발생하는 warning 해결 

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/547 에 대한 pr입니다.
한국시간으로 제목 아래 타임스탬프가 출력되는 것을 확인했습니다.
=> [FEAT] 차트 이미지에 생성 시각(타임스탬프) 출력 기능 추가

reposcore/__main__.py, tests/test_main.py
#502 [BUG] 잘못된 토큰을 입력해도 정상적으로 작동
**Version**
https://github.com/oss2025hnu/reposcore-py/commit/1c159711a4db7b56fb2da9c5aa8aac38e99bc61a
**변경 사항***
못된 토큰을 입력시 `❌ 인증 실패: 잘못된 GitHub 토큰입니다. 토큰 값을 확인해 주세요.` 오류 메시지 출력 후 종료
=> [BUG] 잘못된 토큰을 입력해도 정상적으로 작동에 대한 PR입니다.

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/539
현재 `collect_PRs_and_issues` 메서드에서 GitHub API 에러 처리 코드가 중복되어 있어 코드의 가독성과 유지보수성이 떨어집니다. 각 상태 코드(401, 403, 404 등)마다 거의 동일한 에러 처리 로직이 반복되어 있어 헬퍼 메서드로 분리하여 코드 중복을 제거하여 가독성을 향상 시켰습니다. 
7985798ad0bdb17a94cb9c3a4c8bf16331bd4792
`self._handle_api_error`를 추가하여 코드를 더욱 간략하게 수정하였습니다.
=> [REFACTOR] analyzer.py 중복 오류 처리 수정

reposcore/__main__.py, reposcore/analyzer.py, reposcore/utils/theme_manager.py
https://github.com/oss2025hnu/reposcore-py/issues/538 에 대한 PR
https://github.com/oss2025hnu/reposcore-py/commit/8796e891a7b4e7a6ce04b997ebdfd3cc206e2005
- `ThemeManager` 클래스 도입 (utils/theme_manager.py)
- `RepoAnalyzer` 클래스에서 테마 적용 가능하도록 `theme` 인자 추가
- `generate_chart`, `generate_text` 함수에 테마 기반 스타일 적용
- CLI 옵션에 `--theme` / `-t` 추가 (선택: `default`, `dark`)
- `default`, `dark` 2가지 기본 테마 제공
---
```bash
python -m reposcore oss2025hnu/reposcore-py --format chart --theme dark
```
=> 테마 매니저 기능 구현 및 CLI --theme 옵션 추가

reposcore/__main__.py, reposcore/analyzer.py, reposcore/utils/github_utils.py
[FEAT] check_github_repo_exists() 중복 정의 제거 #468
04b6156
a05a317
- check_github_repo_exists() 함수를 utils/github_utils.py로 분리
- bypass 옵션을 추가해 테스트용(True), 실제검사용(False)으로 구분
- __main__.py는 실제 검사, analyzer.py는 테스트 우회
- analyzer의 더미 함수 제거 및 중복 정의 해소
=> [FEAT] check_github_repo_exists 유틸 함수로 분리 및 bypass 처리 추가

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/549
3bdc04d56acb80f5c34861f372aede5507d46596
`generate_chart` 메서드에서 사용자 이름 앞에 등수를 영어 서수 형식으로 추가했습니다.
"1st joon0447", "2nd Jae-Hyuk-Lee"와 같은 형식으로 표시됩니다.
등수는 1등부터 3등까지는 각각 "1st", "2nd", "3rd"로 표시되며, 4등부터는 "4th", "5th"와 같은 형식으로 표시됩니다.
차트의 막대에 표시되는 텍스트에서 등수는 제거되고, 점수와 등급만 표시됩니다.
차트의 가독성이 향상되어 사용자가 자신의 순위를 더 쉽게 파악할 수 있도록 개선하였습니다.
차트 스크린샷을 함께 첨부하겠습니다.
=> [FEAT] 차트에 직관적인 등수 포맷 및 이름 앞 순위 표기 기능 추가에 대한 PR (#549)

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/537 [FEAT] score.text 파일의 이름 앞 점수별 이모(뱃지)지 추가 에 대한 PR입니다.
eb69211ad681463138a218185e7755bdc2bee230
score.txt파일 내부 결과값에 이름 옆에 점수별 이모지를 추가하였습니다.
=> [FEAT] score.text 파일의 이름 앞 점수별 이모(뱃지)지 추가 에 대한 PR

reposcore/__main__.py, reposcore/analyzer.py, tests/test_analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/546
c8828e7c66de97e67235014f03cf2564de3c905a
generate_table() 함수에서 점수 테이블(score.csv)과 카운트 테이블(count.csv) 생성이라는 두 가지 책임을 분리했습니다.
새로운 generate_count_csv() 함수를 만들어 활동 개수 기반 CSV 파일 생성을 담당하게 했습니다.
generate_count_csv() 함수는 파일 경로를 반환하도록 설계하여 main에서 모든 csv 생성 로직을 호출하도록 설계를 일관화했습니다.
새로운 test_generate_count_csv_creates_file() 테스트를 추가하여 count.csv가 올바르게 생성되는지 확인하였습니다.
아래 명령어를 터미널에서 실행합니다.
``` 
pytest tests/test_analyzer.py -k test_generate_count_csv_creates_file 
```
해당 로직에 대한 테스트가 올바르게 통과되는 것을 확인하였습니다.
=> [REFACTOR] count.csv의 생성을 generate_table()에서 분리에 대한 PR (#546)

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/568
ffab28d3f3a12291a1791cd3dc6b035cf91381eb
- 출력되는 그래프의 1등점수+30점 으로 가로축의 최대범위를 늘려서 글자가 잘리지 않도록 만들었습니다.
=> [BUG] 차트에 비율 표기 부분이 잘려서 표기 에 대한 PR

reposcore/__main__.py, reposcore/analyzer.py, reposcore/utils/github_utils.py
https://github.com/oss2025hnu/reposcore-py/issues/574
01ceda6a1a2207918a936f0275ed4a383f6d82a2
1. reposcore/utils/github_utils.py
- `check_github_repo_exists(repo)` 시 사용되는 bypass 파라미터를 제거 하였습니다.
2. reposcore/analyzer.py
- `__init__` 에서
- repo_path가 "dummy/repo" 이면 테스트용 저장소로 처리합니다.
- repo_path가 "multiple_repos" 이면 통합 분석으로 처리합니다.
- 위 둘 모두일 때(실제로 존재 하지 않는 저장소) `check_github_repo_exists`의 호출을 건너뛰어 `RepoAnalyzer` 클래스 내부에서 예외 처리하도록 구조를 개선하였습니다.
3. 기존 테스트(`tests/test_analyzer.py`, `tests/test_main.py`)를 모두 올바르게 통과하는 것을 확인하였습니다
```
make test
```
=> [REFACTOR] 테스트 코드에서 RepoAnalyzer가 더미 저장소에 대한 예외적 동작을 할 수 있도록 코드 정리 필요에 대한 PR (#574)

.devcontainer/devcontainer.json
https://github.com/oss2025hnu/reposcore-py/issues/587
https://github.com/oss2025hnu/reposcore-py/commit/7db0aa2ecd25ba49b36724930693ddcea7cae136
- `.devcontainer/devcontainer.json` 파일에 `njpwerner.autodocstring` 확장 추가
- autoDocstring 확장 기본 설정을 포함 (google 스타일, Enter 입력 시 생성, 삼중따옴표 사용)
=> Codespace 환경에서 autoDocstring 확장을 자동 설치하도록 devcontainer 설정 추가

README.md, reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/599
https://github.com/oss2025hnu/reposcore-py/commit/fbfb21c67786edb47fdf1ebcfd9f5bb41710a55e
- --help 출력에서 --format 옵션 기본값이 all 이라는 내용 추가
```
--format {table, text, chart, all} [{table, text, chart, all} ...]
결과 출력 형식 선택 (복수 선택 가능, 예: --format table chart)
(기본값:'all')
```
=> --help 출력에서 --format 옵션 기본값이 all 이라는 내용 추가

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/608
c4999730aca3029052f72b07ad7991dbba9cccea
변경 전: "1st username", "2nd username" 등
변경 후: "username (1st)", "username (2nd)" 등
이슈에서 보여준 예시처럼 이름이 먼저 나오고 뒤에 괄호 안에 순위가 표시되도록 기능을 수정하였습니다.
=> [FEAT] 차트에서 "순위 이름" 대신 "이름 순위"로 나타나도록 변경에 대한 PR (#608)

docs/korean-timezone-guide.md
https://github.com/oss2025hnu/reposcore-py/issues/613
d7c5f95e8ed6ec32e87ef37c5981d95dabd48a9c
- GitHub Actions 워크플로우 시간대 설정 섹션 삭제 (Codespaces와 무관).
- devcontainer.json을 통한 한국 시간대(Asia/Seoul) 설정 방법 추가.
- 기존 .bashrc 설정과 주의사항 유지.
=> [DOC] 한국 시간대 설정 가이드에서 workflow 내용 대체 필요 에 대한 PR

reposcore/__main__.py, reposcore/analyzer.py, reposcore/output_handler.py, tests/test_analyzer.py
#618
35deb5d
- analyzer.py에서 출력 관련 코드를 output_handler.py로 이동
- 등급 계산 로직을 output_handler.py로 이동
- CSV, 텍스트, 차트 출력 시 등급 계산 방식 통일
- readme의 로직과 실제 로직이 달라서 test시 결과가 다르게 나오는데 다른 인원의 점수를 위해 수정하지 않음
=> 출력 관련 코드를 output_handler.py로 분리

Makefile
#624 
a0f72681ef87aacc684ed88a54d4102410702852
기존 Makefile 안에 install-fonts가 실제로 폰트를 설치하지 않아서 한글이 깨지게 됨
Makefile 안에 install-fonts 코드를 사용하고 있는 OS에 맞게 폰트를 설치해주는 코드로 수정함
차트 한글 폰트 깨짐 이슈 해결 가이드를 참고하여
make install-fonts
make update-fonts 순으로 적용하여 결과를 출력하여 확인하면 차트도 한글이 깨져보이지 않음을 확인함
=> [BUG] 차트 한글 폰트 깨짐 이슈

reposcore/__main__.py, reposcore/analyzer.py, reposcore/common_utils.py, reposcore/output_handler.py
[FEAT]프로그램 실행 시 CLI창에 출력되는 참여자별 활동 내역 (participants 딕셔너리)을 선택적 표시 옵션 추가 요청 https://github.com/oss2025hnu/reposcore-py/issues/469 및
--user 옵션으로 본인 닉네임 입력 시 총점과 등수 출력 기능 추가 https://github.com/oss2025hnu/reposcore-py/issues/643 에 대한 PR입니다.
750b7e62f542d77672c74951d655735c1e4ec446
issue 및 교수님의 말씀에 따라 -v 또는 --verbose 옵션을 추가하여 participants 딕셔너리를 로그 내역에서 선택적으로 출력할 수 있도록 수정했습니다.
추가로 --user (유저명) 명령어 입력 시 원하는 유저의 정보만 출력하도록 하였습니다.
```python -m reposcore oss2025hnu/reposcore-py --user Sernn0```
```
[2025-05-01 14:23:32] [INFO] 사용자: Sernn0
[2025-05-01 14:23:32] [INFO] 총점: 18.00점
[2025-05-01 14:23:32] [INFO] 등수: 13등 (전체 69명 중)
=> -v, --verbose, --user (유저명) 옵션 추가

reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/653
d479be4fb300ec388224ec6f00d57f60cca588fc
현재 시간을 계산하는 get_kst_timestamp() 함수 추가 후
table, text, csv, chart에 결과 출력 시점의 시간이 출력되도록 함
=> 결과물 생성시간 추가

.devcontainer/devcontainer.json
.devcontainer에 Rainbow CSV 추가 https://github.com/oss2025hnu/reposcore-py/issues/667 에 대한 PR입니다.
66a57e47f1af157b656d934def90180cf3f52ad2
.devcontainer에 ``"mechatroner.rainbow-csv"``코드를 추가해 Rainbow CSV 확장 프로그램이 자동으로 설치되도록 하였습니다.
=> Rainbow CSV 확장 프로그램 자동 설치 목록 추가

reposcore/__main__.py, reposcore/output_handler.py
#654 
6ee4d1665c6852b7b627c6e4969753b3403307d6
results/에 overall_repository 디렉토리를 만들고 저장소마다 기여도를 확인할 수 있는 csv, txt, chart 를 생성함
각 파일을 통해 어느 저장소에서 몇 점을 올렸는지 확인 가능
* csv
* txt
* chart
=> 저장소별 overall 추가

reposcore/__main__.py, reposcore/analyzer.py, reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/650
d443353954bebf2e693160f058e028349c55f3ca
* --weekly-chart 옵션 추가: 학기 시작일(--semester-start)을 기준으로 주차별 활동량(merged PR + 처리된 Issue)을 시각화
* 저장소별 weekly_activity.png 차트 생성
* results/overall/weekly_activity.png 파일로 전체 저장소를 통합한 주차별 활동량 차트 생성
예시)
=> 학기 시작일 기준으로 주차별 활동량 변화 추이 시각화 기능 추가

README.md, template_README.md
#685 make clean 명령어 문서화 필요
https://github.com/oss2025hnu/reposcore-py/commit/4d6a6c3799f8ef1bd51afd5567bd949aed622840
template_README.md 파일에 make clean 명령어에 대한 설명 섹션을 추가하였습니다.
해당 명령어는 results/ 디렉토리를 삭제하여 분석 결과를 초기화할 수 있는 기능을 제공합니다.
make readme 명령어를 실행하여 위 변경 내용을 README.md에 반영하였습니다.
=> make clean 설명 추가

reposcore/__main__.py
하나의 저장소 결과 출력 시 overall_repository 생략 #704
13d9fbf
- 저장소가 하나일 경우, `overall_repository` 디렉토리 및 관련 결과 파일 생성을 생략하도록 조건문 추가
=> [FEAT] 하나의 저장소 결과 출력 시 overall_repository 생략

reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/706
41c89afc71da94d637a017fc10776b01c5c05176
텍스트 출력 결과(`score.txt`)에 참여자별  등수(Rank) 정보를 새로 추가했습니다.
순위는 `enumerate(sorted(...), start=1)`를 사용하여 자동 부여하며, 각 행의 가장 앞 열에 표시됩니다.
=> txt에 등수 추가

README.md, docs/dependency_guide.md, reposcore/__main__.py, requirements.txt, template_README.md
#696 
41c89afc71da94d637a017fc10776b01c5c05176
1. 진행률 표시 기능 추가 (tqdm 적용)
- 저장소별 분석 루프에 tqdm을 적용하여 전체 진행 상황을 막대(bar)로 표시
2. 개별 파일 저장 로그 정리
- csv, txt, chart의 개별 파일 저장 로그는 --verbose 옵션을 사용할 때만 상세히 출력
- 기본 실행 시 저장소별 "결과 저장 완료" 요약 로그만 출력
3. 캐시 관련 설명성 로그 정리
- 저장소 분석 시 저장소마다 캐시를 사용하지 않거나 캐시 파일이 없는 경우의 안내 로그가 반복 출력됨
- 캐시를 사용하지 않거나 캐시 파일이 없는 경우 안내 로그를 --verbose 옵션을 사용할 때만 출력하도록 변경
- 캐시를 성공적으로 사용할 때는 기존처럼 안내 로그를 출력 (정상 동작 여부는 항상 표시)
4. 통합 저장소(overall_repository) 결과 안내 추가
- 전체 통합 분석이 완료되면 사용자별 기여도는 결과 파일에서 확인할 수 있다는 안내 문구 추가
* 요약
- 코드 실행 시 오류 없음
- verbose 옵션을 통해 상세 로그 출력 가능
- 기본 실행 시 불필요한 중복 로그 최소화하여 깔끔하게 출력
* 주의사항
- 진행률 표시를 위해 tqdm 라이브러리가 필요
- 본 PR은 코드 반영만 포함, requirements.txt 및 README에 설치 가이드 반영은 별도의 이슈 필요
* 여러 저장소 분석 시
* 단일 저장소 분석 시
=> [FEAT] 여러 저장소 분석 시 반복적인 파일 저장 로그 통합

reposcore/__main__.py, reposcore/output_handler.py
#694 
6c379f21d502ffbae2c25d09251c57bb576cd76f
OutputHandler 등에서 matplotlib이 즉시 로딩되면서 발생하는 문제로
make readme 명령어 실행 시 발생하던 '[INFO] generated new fontManager' 로그를 제거했습니다.
main.py 파일에서 OutputHandler, common_utils import 위치를 main() 함수 내부로 이동했습니다.
matplotlib 캐시 삭제 후 make readme 명령어 실행 테스트 했을 시 
기존에 뜨던 로그가 출력 안되는 것을 확인했습니다.
나머지 코드들도 정상 작동 확인했습니다.
=> [BUG] make readme 시 불필요한 fontManager 로그 출력됨

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/708
6c379f21d502ffbae2c25d09251c57bb576cd76f
`--user` 옵션 사용 시 단일 저장소만 분석되던 문제를 수정하고, **여러 저장소 입력 시 전체 통합 기준으로 점수 및 등수를 출력**하도록 변경하였습니다.
- 사용자 점수 출력 위치를 모든 로그 출력 이후, 맨 아래로 이동시켜 가독성을 개선했습니다.
- 로그 대신 `print()`를 사용하여 터미널에서 줄바꿈 및 명확한 시각적 구분을 가능하게 했습니다.
- 단일 저장소는 파일이 안만들지만 여러 저장소를 할 경우 파일이 생성됩니다.
출력 예시
=== 전체 저장소 통합 분석 ===
[2025-05-15 11:29:27] ℹ️ [통합 분석] 여러 저장소의 통합 분석을 수행합니다.
[2025-05-15 11:29:29] [통합 저장소] 분석 결과(CSV, TXT, Chart) 저장 완료: results/overall
[2025-05-15 11:29:31] [📊 overall_repository] 분석 결과(CSV, TXT, Chart) 저장 완료: results/overall_repository
[2025-05-15 11:29:31] [📊 overall_repository] 통합 저장소 기준 사용자별 기여도는 'results/overall_repository' 폴더 내 결과 파일에서 확인할 수 있습니다.
[2025-05-15 11:29:31] [INFO] 사용자: jungsuryeon
[2025-05-15 11:29:31] [INFO] …
=> [BUG] --user 옵션 사용 시 하나의 저장소 결과만 출력되는 문제 해결

reposcore/output_handler.py
#703 
5e9045f2d156fd223cd17f13afb6a70faf828066
overall_repository 에 생성되는 차트의 막대그래프 옆에도
숫자로 자신의 총 점수가 몇인지 확인할 수 있게 수정했습니다.
=> overall_repository 차트 개별 막대그래프 옆에 수치 표시

reposcore/analyzer.py, tests/test_analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/729
69fe5776314fa4d70e39f78a15b6e6b49cf9d14d
- PR이 전혀 없는 사용자가 이슈만 작성한 경우, 기존에는 점수가 아예 계산되지 않는 문제가 있었습니다. 이를 해결하기 위해 다음과 같은 보정 로직을 추가했습니다:
- PR이 0개이지만 이슈가 1개 이상 있는 경우 `p_valid=1`로 간주해 1:4 규칙에 따라 이슈 점수를 인정
- 실제 PR 점수는 **모두 0으로 고정**하여 잘못된 점수 반영을 방지
```python
if p_fb == 0 and i_fb + i_d > 0:
p_valid = 1
i_valid = min(i_fb + i_d, 4 * p_valid)
p_fb_at = 0
p_d_at = 0
p_t_at = 0
i_fb_at = min(i_fb, i_valid)
i_d_at = i_valid - i_fb_at
=> 일부 사용자에게 reposcore-cs 저장소 점수가 미반영

reposcore/analyzer.py, reposcore/retry_decorator.py
(https://github.com/oss2025hnu/reposcore-py/issues/739)
0d431ab788138bbb576288bd1b271d8837ddff7a
해당 이슈에서 제기된 retry_request() 호출 시 max_retries 인자를 전달해 TypeError가 발생하는 문제를 수정했습니다.
reposcore/analyzer.py에서 retry_request(..., max_retries=3) 호출 부분을 max_retries 인자 없이 호출하도록 수정했습니다.
reposcore/github_utils.py에 @retry(max_retries=3, retry_delay=2)를 사용해 재시도 로직이 내장된 retry_request() 함수를 정의했습니다.
이후 테스트가 성공적으로 완료되는것을 확인했습니다.
[2025-05-22 07:17:44] oss2025hnu/reposcore-py 분석 결과(CSV, TXT, Chart) 저장 완료: results/oss2025hnu_reposcore-py
저장소 분석 진행: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.64s/it]
[2025-05-22 …
=> [BUG] analyzer.py에서 retry_request() 호출 시 max_retries 매개변수로 인한 TypeError 발생 #739 에 대한 pr입니다.

reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/700
7c8649e148dc14ae4fa2d3ac5d78bdd6fc1ad82e
그래프에서 한글을 출력 시 경고가 발생하던 문제를 그래프에서 사용하던 한글을 모두 영어로 바꾸어 해결하였습니다.
변경된 한글 -> 영어는 다음과 같습니다.
분석 기준 시각 -> Generated at
점수 -> Score
사용자별 저장소 기여도 -> Repository Contribution Scores
주차 -> Week
건수 -> Count
주차별 GitHub 활동량 -> GitHub Activity per Week
=> 그래프 한글 출력 시 경고 발생 문제 해결

reposcore/output_handler.py
(https://github.com/oss2025hnu/reposcore-py/issues/757)
7ec9a798b1c00b6a04f35190ed8ac9ce07b02326
output handler. generate_chart() 내부에서 rank필드가 누락된 입력에서도 제대로 작동하도록 방어로직을 추가했습니다.
**테스트 시행후 결과가 제대로 생성되는것을 확인했습니다**
[2025-05-24 14:32:17] 저장소 분석 시작: oss2025hnu/reposcore-py, oss2025hnu/reposcore-js, oss2025hnu/reposcore-cs
저장소 분석 진행:   0%|                                                                                                                                                                                                                              | 0/3 [00:00<?, ?it/s][2025-05-24 14:32:24] oss2025hnu/reposcore-py 분석 결과(CSV, TXT, Chart) 저장 완료: results/oss2025hnu_reposcore-py
저장소 분석 진행:  33%|███████████████████████████████████████████████████████████████████████▎ …
=> [BUG] _generate_score_table_html 함수 버그 #757 에 대한 pr입니다.

reposcore/__main__.py
https://github.com/oss2025hnu/reposcore-py/issues/764
471c7821af912943cd6a148b08d3e05398418d90
기존 html 에서 생성되던 overall repository의 테이블이 정렬이 되지 않고, 순위가 표시되지 않던 문제를 해결하였습니다.
`__main__.py`의 overall repository의 딕셔너리에 해당하던 user_scores를 정렬하는 코드와 rank값을 삽입하는 코드를 추가하였습니다.
수정이후 테이블이 올바르게 출력되는 모습을 보입니다.
=> html overall repository 정렬 및 순위표시

reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/788
c6b58901b1b0ca7df3f62b8fec3c4086632a2e41
변경전
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
변경 후
timestamp = self.get_kst_timestamp()
HTML 보고서 상단의 생성 일시가 차트 생성 시간과 일치하게 되고, 한국 시간(KST) 기준으로 일관되게 표현되게 했습니다.
=> HTML의 생성 시간 수정

reposcore/common_utils.py
https://github.com/oss2025hnu/reposcore-py/issues/794
c6b58901b1b0ca7df3f62b8fec3c4086632a2e41
common_utils.py의 log() 함수에서 zoneinfo 모듈을 통해 Asia/Seoul 시간대를 적용하도록 수정했습니다.
=> 터미널 상의 시간 로그 오류 수정

reposcore/analyzer.py, tests/test_analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/795 에 대한 PR입니다.
57d655e
기존 오류가 있던 RepoAnalyzer.calculate_scores() 계산식을 수정하여
문서 PR과 문서 이슈가 모두 있는 경우, 예상 점수(3점)와 다르게 1점만 계산되는 문제를 수정하였습니다.
=> [BUG] 하위권 user 의 점수가 js와 py 점수 차이에 대한 PR 

reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/793
57d655e63166bc6be1cb9f303777b73994f59d7b
generate_chart() 내 ax.text() 출력 방식 개선
점수(total)가 낮은 경우(<= 3) 텍스트를 오른쪽으로 더 멀리 띄움 → 겹침 방지
텍스트 형식을 2줄로 줄바꿈 → 점수/등급과 비율을 분리 출력
label = f'{total:.1f} ({grade})\nP:{int(pr_ratio*100)}% I:{int(issue_ratio*100)}%'
x_offset을 막대 길이에 비례한 비율(2%)로 조정
폰트 크기를 살짝 줄여(fontsize=8) 밀집 구간에서도 잘 보이도록 개선
=> 차트 텍스트가 막대와 겹치는 현상 수정

docs/debug_guide.md
#690 [DOC] docs/debug_guide.md에 verbose 로깅 및 테스트 캡처 섹션 추가
https://github.com/oss2025hnu/reposcore-py/commit/57d655e63166bc6be1cb9f303777b73994f59d7b
-v/--verbose 옵션 활성화 방법 및 로그 레벨 DEBUG/INFO 구분 설명,
CI나 subprocess.run() 사용 시 stderr=subprocess.STDOUT 옵션을 통해 stderr를 stdout으로 합쳐 캡처하는 예시 코드,
테스트 환경에서 stdout만 검사할 때 발생할 수 있는 문제와 그 해결책 작성
=> docs/debug_guide.md에 verbose 로깅 및 테스트 캡처 섹션 추가

reposcore/__main__.py, reposcore/output_handler.py
https://github.com/oss2025hnu/reposcore-py/issues/785
57d655e63166bc6be1cb9f303777b73994f59d7b
- overall 통합 점수 결과에서 동점자 동일 순위 처리(1, 2, 2, 4...) 적용하도록 변경
- overall_scores.csv, overall_scores.txt, overall_chart.png, HTML 보고서 등 모든 출력에 반영됨
|  7   |   jungsuryeon    |            47           |            62           |            2            |  111  |
|  8   |   Jae-Hyuk-Lee   |            33           |            77           |            0            |  110  |
|  9   |    bym010312     |            72           |            36           |            0            |  108  |
|  9   |    jaewon786     |            68           |            40           |            0            |  108  |
|  11  |    kjason0102    |            70           |            23           |            0            | …
=> [BUG] overall_repository 동점자 등수 처리 오류 에 대한 pr입니다.

reposcore/output_handler.py
테이블의 실수 표기 방식 변경 https://github.com/oss2025hnu/reposcore-py/issues/791 에 대한 PR입니다.
5b627b379cfc71abb2bf122a0af8750387cc640a
txt 파일을 생성하는 코드를 아래와 같이 수정
```bash
f"{score['total']:5.1f}" -> int(score['total'])
```
보이는 것 뿐 아니라 값을 완전히 정수형으로 바꾸기 위해 형변환을 사용
=> 텍스트 파일 결과물의 실수형 포맷팅을 정수형으로 형변환

reposcore/__main__.py
#776 
f6007c94046c0235743c55c49e6f56e6593d81e3
- 사용자가 실행한 CLI 옵션들을 results/settings.json 파일로 저장하는 기능을 추가했습니다.
- argparse로 파싱된 args 객체를 json 형태로 직렬화하여 분석 결과 디렉토리에 함께 저장됩니다.
- 실행 조건 재현이 가능하도록 CLI 실행 이력을 남기는 기능입니다.
```bash
python -m reposcore oss2025hnu/reposcore-py --format chart --use-cache --dry-run
```
```json
{
"repository": [
"oss2025hnu/reposcore-py"
],
"verbose": false,
"output": "results",
"format": [
"table"
],
"grade": false,
"use_cache": true,
"token": null,
"check_limit": false,
"user_info": null,
"user": null,
"theme": "default",
"weekly_chart": false,
"semester_start": null,
"min_contributions": 1,
"dry_run": true
}
=> 분석 시 사용된 CLI 옵션 로그로 저장

reposcore/analyzer.py
https://github.com/oss2025hnu/reposcore-py/issues/820
314612ec32686d1e8837cd11a9b7e5dfb2fb21d6
calculate_scores 함수와 _finalize_scores 함수에서 user_info 매핑이 두 번 일어나면서 두 번째 매핑 시점에 scores가 비어 오류가 
발생했기 때문에 calculate_scores 함수의 user_info 매핑 부분을 제거 했습니다.
=> bug: --user-info 에러 해결

reposcore/__main__.py
#709 
fef94bf
handle_individual_user_mode 함수에서 RepoAnalyzer.collect_PRs_and_issues() 호출 전에 저장소 포맷(validate_repo_format)과 저장소 존재 여부(check_github_repo_exists) 검사를 추가했습니다.
=> API 호출 전에 저장소 포맷 및 존재 여부 검사 추가
