oss2025hnu/reposcore-py

_people_.txt

https://github.com/oss2025hnu/reposcore-py/issues/22
위 issues 에 해당하는 txt 내용 추가합니다!
충돌 확인 해주세요~

Update _people_.txt -> 장나영 정보 추가

---

_people_.txt

https://github.com/oss2025hnu/reposcore-py/issues/6
위 이슈 해결

Update _people_.txt : 충돌해결 4트째

---

_people_.txt

위 이슈를 해결하기 위해
정수련 jungsuryeon 정보를 .people.txt에 추가
https://github.com/oss2025hnu/reposcore-py/issues/7

Update _people_.txt 1

---

_people1_.txt

박용성 정보를 _people1_.txt에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/154
정문경 정보 _people2_.txt에 추가

정문경 정보 _people2_.txt에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/113 위 이슈를 해결하기 위해 정보를 추가했습니다.

한성준 정보를 _people2_.txt에 추가

---

_people1_.txt

https://github.com/oss2025hnu/reposcore-py/issues/121
위 이슈를 해결하기 위해
정동우 정보를 _people1_.txt에 추가

정동우 정보를 _people1_.txt에 추가

---

_people1_.txt

https://github.com/oss2025hnu/reposcore-py/issues/135
위 이슈를 해결하기 위해
안기영 정보 people1.txt에 추가

유지현 정보 _people1_.txt에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/130
위 이슈를 해결하기 위해
고우진 정보 _people2_.txt에 추가

고우진 정보 _people2_.txt에 추가

---

_people1_.txt

https://github.com/oss2025hnu/reposcore-py/issues/120
위 이슈를 해결하기 위해
김지혜 정보 _people1_.txt에 추가

김지혜 정보 _people1_.txt에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/148
위 문제를 해결하기 위해
안현준 깃허브계정 추가

안현준 _people2_txt 파일에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/123
위 이슈를 해결하기 위해
김재승 정보가 _people2_.txt에 추가

김재승 정보가 _people2_.txt에 추가

---

_people1_.txt

https://github.com/oss2025hnu/reposcore-py/issues/182
위 문제를 해결하기 위해
홍성민 정보 _people1_.txt에 추가

홍성민 정보가 _people1_.txt에 추가

---

_people2_.txt

https://github.com/oss2025hnu/reposcore-py/issues/192
위 문제를 해결하기 위해
최현민 정보 people2. txt에 추가

최현민 정보가 _people2_.txt에 추가

---

_people2_.txt

#124
위 이슈를 해결하기위해
손정헌 정보 _people2_.txt에 추가

손정헌 정보가_Update _people2_.txt

---

_people1_.txt

서준용 정보 _people1._txt에 추가
https://github.com/oss2025hnu/reposcore-py/issues/114

서준용 정보 _people1._txt에 추가

---

_people1_.txt

[#138](https://github.com/oss2025hnu/reposcore-py/issues/138)
위 문제를 해결하기 위해
강규혁 정보 people1.txt에 추가

강규혁 정보 _people1_.txt에 추가

---

_people2_.txt

위 이슈를 해결하기 위해
https://github.com/oss2025hnu/reposcore-py/issues/221

윤여명 정보 _people2_.txt

---

_people1_.txt

이상훈 정보 people1.txt에 추가
위 이슈를 해결하기위해
https://github.com/oss2025hnu/reposcore-py/issues/115

이상훈 정보를 _people1_.txt에 추가

---

_people1_.txt

윤은우 정보를 people1_.txt에 추가
위 이슈를 해결하기 위해
https://github.com/oss2025hnu/reposcore-py/issues/251

윤은우 정보 _people1_.txt에 추가

---

README.md
reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/272 --help 메시지에 나오는 --repo REPO 부분 개선 이슈에 대한 PR입니다.
23967129f13c177226c0d42c2acdd607e3764486
Describe alternatives you've considered
metavar를 활용해서 usage 파라미터를 명시해 가독성을 개선합니다.

[STYLE] --help 메시지 개선

---

Makefile
README.md
reposcore/__main__.py
tests/__init__.py
tests/test_analyzer.py
tests/test_main.py

https://github.com/oss2025hnu/reposcore-py/issues/273 [BUG] 정상적인 --repo 옵션으로 실행시켜도 Error로 비정상 종료 에 대한 PR입니다.
Specify version (commit id). 23967129f13c177226c0d42c2acdd607e3764486
**변경사항**
- 오류가 발생하여도 비정상적으로 종료되는 현상을 막고자 테스트 템플릿 추가.
- '__main__.py'에 있는 불필요한 'collect_commits()' 관련 출력물 변경.
- 'README.md'개선
1. 'pytest'기반 테스트 실행 방법 문서화
2. 테스트 템플릿 예시 추가
3. 테스트 결과 읽는 방법 설명
**Describe alternatives you've considered**
-앞으로 작업물에 기능 추가 시 테스트 파일에 케이스를 추가하고 테스트를 진행할 수 있습니다.

[BUG] 정상적인 --repo 옵션으로 실행시켜도 Error로 비정상 종료 에 대한 PR

---

README.md

https://github.com/oss2025hnu/reposcore-py/issues/277 [DOC] Score Formula 단순화 (기능과 버그 관련 변수를 통합) 에 대한 PR입니다.
Specify version (commit id). f31267398a7faafc709fd636ebd3cf8a91f637aa
**변경사항**
- 기존의 README.md 안의 내용인 Score Formula부분에 대한 식을 더욱 간단히 나타내었습니다.

[DOC] Score Formula 단순화 (기능과 버그 관련 변수를 통합) 에 대한 PR

---

reposcore/analyzer.py

#284 `[REFACTOR] collect_PRs_and_issues 함수를 개선해주세요.` 에 대한 PR
Specify version (commit id) [8d34f81ff7e8057010f7d669db9f82f110846a8a](https://github.com/oss2025hnu/reposcore-py/commit/8d34f81ff7e8057010f7d669db9f82f110846a8a)
변경사항
collect_PRs_and_issues함수에서 요청하는 Github API추가 및 계산식 개선
Describe alternatives you've considered
Score Formula 기준인 기능/버그, 문서 분류(P_fb, P_d, I_fb, I_d)는 반영했습니다.

[REFACTOR] collect_PRs_and_issues 함수를 개선해주세요. - collect_PRs_and_issues 함수 개선

---

reposcore/analyzer.py
reposcore/utils/retry_request.py

#316 GitHub API 호출 실패 시 자동 재시도 기능 추가에 대한 PR입니다.
**Version (commit id)**
https://github.com/oss2025hnu/reposcore-py/commit/e19389858589bd03ae04888d11b1529c5418a083
reposcore프로그램 동작에 불필요한 코드 및 Github API요청 실패시 재요청 기능 개발했습니다.

GitHub API 호출 실패 시 자동 재시도 기능 추가에 대한 PR입니다.

---

tests/test_analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/309 generate_table, generate_chart가 실제로 파일을 생성하는지 테스트 추가에 대한 PR입니다.
https://github.com/oss2025hnu/reposcore-py/commit/239671
**추가사항** 
reposcore/analyzer.py의 generate_table()과 generate_chart() 함수가 정상적으로 파일을 생성하는지 확인하는 테스트를 tests/test_analyzer.py에 추가했습니다.
다음과 같은 사항에 대해 테스트를 작성했습니다:
- generate_table 실행 후 CSV 파일이 생성되는지 확인
- generate_chart 실행 후 PNG 이미지 파일이 생성되는지 확인
모든 테스트는 tempfile을 이용하여 임시 디렉토리에서 수행되며,  
테스트 종료 후 파일은 자동으로 삭제됩니다.
Test Result  
make test 명령어를 통해 모든 테스트가 정상적으로 통과했음을 확인했습니다.

generate_table 및 generate_chart의 파일 생성 테스트 추가

---

reposcore/__main__.py

오타 수정에 대한 PR입니다.
879763340d50bac89a79522c5e56030861b5d97d
- `main.py` 64번째 줄에서 `parser.add.argument` 오타를 `parser.add_argument`로 수정했습니다.

[STYLE] 오타 수정

---

reposcore/__main__.py
reposcore/analyzer.py

[FEAT] scores 와 scores_temp 통합 및 관련 함수 수정 요청. #326
Specify version (commit id) https://github.com/oss2025hnu/reposcore-py/commit/281e676b43fbd8de2b3825de2d5dd17c1fa81159
**변경사항**
- analyzer.py 불필요한 import문 제거
- socres_temp변수 제거 및 scores변수로 통합함.

[FEAT] scores 와 scores_temp 통합 및 관련 함수 수정 요청에 대한 PR입니다.

---

README.md
reposcore/__main__.py

#374 [DOC] CLI 옵션 설명(--format) 수정 필요 
**Specify version (commit id)**
https://github.com/oss2025hnu/reposcore-py/commit/9b95ad23d163106dbb6fad309748a2c77577a7af
**변경사항**
- `README.md` 문서의 `--format`옵션 코드와 일치하도록 수정

[DOC] CLI 옵션 설명(--format) 수정 필요에 대한 PR입니다.

---

README.md

[DOC] Readme usage 불필요 코드 삭제 https://github.com/oss2025hnu/reposcore-py/issues/387 에 대한 수정 PR 입니다.
c10552f9b5bd6122df0768972b8fc0d8c79188ca
**변경사항**
README.md의 usage부분에 불필요한 코드를 제거하였습니다.

README.md의 usage부분 불필요 코드 제거

---

reposcore/__main__.py
reposcore/analyzer.py

#389 output 디렉토리 생성 중복 제거 
https://github.com/oss2025hnu/reposcore-py/commit/c10552f9b5bd6122df0768972b8fc0d8c79188ca
**변경 사항**
output 디렉토리 생성 중복코드 제거

output 디렉토리 생성 중복 제거 

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/413 이슈의 중복 사용
d95ed3b28b10e342735482c5b0815501eb9cc84d
변경 사항
os.makedirs(output_dir, exist_ok=True) 중복코드 제거

 [DOC] os.makedirs(output_dir, exist_ok=True) 중복 사용 

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/425 에 대한 pr입니다.
해당부분 변경 완료 하였습니다.

[REFACTOR] chart.png에 표시되는 점수를 실수에서 정수로 변경 요청

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/424
해당 이슈에 대한 pr입니다.
issue에 요청된 변경사항을 처리하였습니다.
또한 테스트를 시행하여 제대로된 결과가 출력되는것을 확인했습니다.

[REFACTOR] 항목별 점수에 대한 상수화 

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/390
에 대한 pr입니다.
pr에서 요청한 변경사항을 적용하였습니다.
테스트 실행후 정상적인 결과가 출력되는것을 확인했습니다.

[DOC] 채점 공식 수정: 기능/버그 PR 0건 시 문서 PR 최대 3건 인정되도록 P_valid 수정 

---

tests/test_analyzer.py

[BUG] test_user2 의 총점 기대값 불일치로 인한 테스트 실패 https://github.com/oss2025hnu/reposcore-py/issues/429 에 대한 PR 요청입니다.
80e6d9020b095dd97a462f510831175b58849112
**변경사항**
p_vaild의 공식 변경 이후 오류를 일으키던 test_user2 의 계산 점수값을 0에서 16으로 수정하였습니다.

test_user2 의 결과값 수정

---

reposcore/__main__.py
reposcore/analyzer.py

#438 [FEAT] 깃허브 API를 사용할 때 403 오류 외에도 다른 오류들이 발생 가능 
https://github.com/oss2025hnu/reposcore-py/commit/80e6d9020b095dd97a462f510831175b58849112
**변경사항**
403 이외 에러 발생시 에러를 핸들링 하는 기능 추가

[FEAT] 깃허브 API를 사용할 때 403 오류 외에도 다른 오류들이 발생 가능에 대한 PR입니다.

---

README.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/440
새 CLI 옵션 및 repository 인자 변경 반영을 위한 문서 업데이트 요청 #440에 대한 pr입니다
commit id
0f68bc8ee0c02cbf601a230163a5f244f23a92cf
변경사항
template_README.md 파일에 새 옵션 사용법에 대한 정보 추가
(--check-limit 옵션 사용 시 저장소 인자를 생략할 수 있으며, 이 옵션을 통해 GitHub API의 잔여 요청 횟수와 전체 한도를 확인할 수 있다는 내용을 명시)

새 CLI 옵션 및 repository 인자 변경 반영을 위한 문서 업데이트 요청 #440

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/446
[FEAT] 저장소에 잘못된 이름을 입력시에 프로그램 실패 코드가 없습니다. 에 대한 pr입니다.
commit id:
e0dfda3cfd3db460ba1b3e617d4af5c363bfd912
변경사항: 잘못된 저장소 입력 시 sys.exit(1)으로 프로그램 실패를 알리는 코드를 추가함.

[FEAT] 저장소에 잘못된 이름을 입력시에 프로그램 실패 코드가 없습니다. 

---

reposcore/__main__.py
reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/449
에 대한 pr입니다
- 디렉토리 생성을 위해 os모듈을 추가하였습니다.
- `os.makedirs(args.output, exist_ok=True)` 추가하여 결과 저장 디렉토리가 없을 경우 자동 생성되도록 수정하였음
-  내부적으로 결과(`chart.png`, `table.csv`, `table.txt`)를 저장할 때도 디렉토리 존재 여부를 확인하고, 없을 경우 생성하도록 수정
-  `generate_table()`, `generate_text()`, `generate_chart()` 함수 내부에서도 저장 경로에 대해 디렉토리 유무를 확인하고 없을 경우 생성되도록 수정
테스트가 정삭적으로 작동되는것을 확인했습니다.

[BUG] 깨끗한 상태에서부터 프로그램 실행하면 캐시 파일 생성 오류 발생 

---

reposcore/analyzer.py

교수님의 데이터를 실제 기여도 평가에서 제거 https://github.com/oss2025hnu/reposcore-py/issues/461 에 대한 PR 요청입니다.
93efd104ded3b1cccba896f1aa4cf310fc7db605
**변경사항**
교수님의 github 아이디(kyahnu, kyagrd)를 participants 딕셔너리에서 제외하여 chart, table 등의 출력값에 포함되지 않도록 수정했습니다.

excluded_ids 추가 PR

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/477 에 대한 pr입니다.
`__main__.py` 파일에서 사용되던 print 기반의 custom log() 함수를 제거하고, Python의 built-in logging 모듈을 사용하도록 전면 변경하였습니다. 이로 인해, 코드 전체에서 로그 출력이 일관되게 처리되며 디버깅 및 유지보수가 용이해집니다.
201b33e3fd3127ca4d859f44679614ba9005c02c
변경사항
`__main__.py` 파일 내의 모든 log() 호출을 `logging.info()`, `logging.error()`, `logging.warning()` 등 적절한 logging 함수로 대체하였습니다.
기타 코드 내 출력 및 에러 처리 메시지도 전반적으로 logging 모듈에 맞춰 수정하였습니다.

[BUG] __main__.py파일 logger적용 안됨 에 대한 PR입니다.

---

.github/workflows/ci.yaml
README.md
docs/chart-font-guide.md
reposcore/__main__.py
reposcore/analyzer.py

#443 [FEAT] 사용자의 정보를 사전에 입력 받아 결과물 출력시 사용자의 ID를 사용자의 이름으로 치환하는 기능 
**Specify version (commit id)**
47c8e34f80a3d2aeb32490bcb49ce008c794bf40
**변경사항**
- 불필요한 코드 제거
- 사용자의 정보를 사전에 입력 받아 결과물 출력시 사용자의 Id를 치환하는 기능
- 사용자 정보 파일에만 정보가 있는 경우 발생하는 에러 수정

[FEAT] 사용자의 정보를 사전에 입력 받아 결과물 출력시 사용자의 ID를 사용자의 이름으로 치환하는 기능에 대한 PR

---

reposcore/analyzer.py

#489
b8e8c98
변경사항
analyzer.py 파일에 정의된 log() 함수를 제거하고, 해당 파일 내의 모든 로그 호출을 logging.info(), logging.warning(), logging.error() 등 적절한 logging 함수로 직접 대체

로깅 방식 통일: analyzer.py의 custom log() 함수 제거

---

README.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/476 수정완료했습니다.

[DOC] readme.md(template_README.md)오탈자 수정 

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/485 에러 처리 개선에 대한 PR입니다.
a5943ad0a45ec2b45ed950a772391cd3f0f0be0c
- 에러 메시지를 딕셔너리 기반으로 리팩토링 했습니다.
ERROR_MESSAGES = {
401: "❌ 인증 실패: 잘못된 GitHub 토큰입니다. 토큰 값을 확인해 주세요.",
403: ("⚠️ 요청 실패 (403): GitHub API rate limit에 도달했습니다.\n"
"🔑 토큰 없이 실행하면 1시간에 최대 60회 요청만 허용됩니다.\n"
"💡 해결법: --api-key 옵션으로 GitHub 개인 액세스 토큰을 설정해 주세요."),
404: f"⚠️ 요청 실패 (404): 리포지토리가 존재하지 않습니다.",
500: "⚠️ 요청 실패 (500): GitHub 내부 서버 오류 발생!",
503: "⚠️ 요청 실패 (503): 서비스 불가",
422: ("⚠️ 요청 실패 (422): 처리할 수 없는 컨텐츠\n"
"⚠️ 유효성 검사에 실패 했거나, 엔드 포인트가 스팸 처리되었습니다.")
}

[REFACTOR] 에러 메시지 처리를 딕셔너리 기반으로 리팩토링

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/493 [FEAT] 분석 결과 파일에 생성 일시 삽입 에 대한 PR입니다.
16498e7e811804f69e4d8430ac12fdf0fe4195a5
**변경사항**
- 차트와 텍스트 파일 좌측 상단에 결과 생성 일시를 삽입하였습니다.

[FEAT] 분석 결과 파일에 생성 일시 삽입 에 대한 PR

---

reposcore/utils/validators.py

59fdadd38bd416ed61cc94d395d50af6e824ec8d
- `reposcore/utils/validators.py` 파일 13번 라인 들여쓰기 오타 수정

[STYLE] 들여쓰기 수정

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/495 [FEAT] analyzer.py의 차트 생성 기능 개선 PR입니다.
**Specify version (commit id)**
https://github.com/oss2025hnu/reposcore-py/commit/c61cc80f389ddc3209efa225de4b3f59dce8413b
**변경사항**
- 하드코딩된 색상 제거
- matplotlib의 colormap 적용
- 차트 유연성 및 가독성 개선

[FEAT] analyzer.py의 차트 생성 기능 개선 PR

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/508 [FEAT] --grade CLI 옵션 지원 에 대한 PR입니다.
Specify version (commit id) c61cc80f389ddc3209efa225de4b3f59dce8413b
**변경사항**
- 막대 그래프에 점수와 함께 등급(A~F)을 표시할 수 있도록 설계하였습니다.

[FEAT] --grade CLI 옵션 지원 에 대한 PR

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/507 에 대한 PR
https://github.com/oss2025hnu/reposcore-py/commit/c61cc80f389ddc3209efa225de4b3f59dce8413b
**변경사항**
- 여러 저장소를 분석할 경우 각 저장소에 대해 별도의 하위 디렉토리를 생성하여
결과물(table.csv, table.txt, chart_participation.png)을 저장하도록 변경
```
results/
├── oss2025hnu_reposcore-cs/
│   ├── chart_participation.png
│   ├── table.csv
│   └── table.txt
├── oss2025hnu_reposcore-js/
│   ├── chart_participation.png
│   ├── table.csv
│   └── table.txt
├── oss2025hnu_reposcore-py/
│   ├── chart_participation.png
│   ├── table.csv
│   └── table.txt
├── chart_participation.png
├── table.csv
└── table.txt
```

저장소별 결과 출력 디렉토리 분리

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/473 중복된 문자열을 상수로 정의에 대한 PR입니다.
49bd79729bd096f93b1c96bddc41a87f6aa8f6c0
- `main.py` 파일에서 자주 사용되는  "table", "text", "chart", "all" 문자열을 상수화 하였습니다.

[REFACTOR] 중복된 문자열을 상수로 리팩토링

---

reposcore/analyzer.py

#519
chart_participation와 chart_participation_grade가 존재할 경우, 파일을 삭제한 후 
--grade키워드가 있을 경우 chart_participation_grade 생성
없을경우 chart_participation생성을 하도록 만들었습니다.
현재  Error: name 'cm' is not defined 이 존재해 import cm as cm을 넣어둔 상태입니다.

[FEAT] 등급 표시 그래프 수정

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/523 [FEAT] 그래프에 등수 추가 에 대한 PR입니다.
Specify version (commit id) 356b54eb354c3da2ffa024a5a7b76f2e197e2cdd
**변경사항**
- 막대그래프 끝에 등수를 표기하였습니다.

[FEAT] 그래프에 등수 추가 에 대한 PR

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/540
- 클래스 레벨 상수 추가
SCORE_WEIGHTS: 점수 가중치 정의
CHART_CONFIG: 차트 관련 설정값 (높이, 너비, 폰트 크기 등)
GRADE_THRESHOLDS: 등급 기준 점수
EXCLUDED_USERS: 제외할 사용자 목록
하드코딩된 값들을 의미 있는 이름의 상수로 정의하였습니다.
```
SCORE_WEIGHTS = {
'feat_bug_pr': 3,
'doc_pr': 2,
'typo_pr': 1,
'feat_bug_is': 2,
'doc_is': 1
}
CHART_CONFIG = {
'height_per_participant': 0.4,  # 참여자당 차트 높이
'min_height': 3.0,             # 최소 차트 높이
'bar_height': 0.5,             # 막대 높이
'figure_width': 10,            # 차트 너비
'label_offset': 0.5,           # 레이블 오프셋
'font_size': 9                 # 폰트 크기
}
GRADE_THRESHOLDS = {
90: 'A',
80: 'B',
70: 'C',
60: 'D',
50: 'E',
0: 'F'
}
```

[REFACTOR] analyzer.py 상수 리팩토링 요청에 대한 PR

---

README.md
template_README.md

#500 README 파일의 점수 계산식에 오타수정 PR을 추가
1c159711a4db7b56fb2da9c5aa8aac38e99bc61a
변경사항:
README 파일의 점수 계산식에 오타수정 PR에 대한 계산식을 추가함

README 파일의 점수 계산식에 오타수정 PR을 추가

---

reposcore/analyzer.py

#541 
해당 PR과 연결된 이슈 ID를 작성해주세요.
eb69211
_extract_pr_counts: PR 관련 카운트 추출
_extract_issue_counts: 이슈 관련 카운트 추출
_calculate_valid_counts: 유효 카운트 계산
_calculate_adjusted_counts: 조정된 카운트 계산
_calculate_total_score: 총점 계산
_create_score_dict: 점수 딕셔너리 생성
_finalize_scores: 최종 점수 계산 및 정렬

[REFACTOR] 점수계산 로직 함수로 치환 요청

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/552
https://github.com/oss2025hnu/reposcore-py/commit/3bdc04d56acb80f5c34861f372aede5507d46596
- --user-info 옵션으로 전달된 경로가 실제 파일인지 확인하는 로직 추가
- JSON 형식이 잘못된 경우 JSONDecodeError를 캐치하여 명확한 에러 메시지 출력
- 정상 실행 예시 (`user_name.json` 정상 파일 사용 시)
```bash
$ python -m reposcore oss2025hnu/reposcore-py --user-info user_name.json --format text
[2025-04-22 10:12:01] [INFO] 저장소 분석 시작: oss2025hnu/reposcore-py
[2025-04-22 10:12:02] [INFO] 분석 시작: oss2025hnu/reposcore-py
[2025-04-22 10:12:04] [INFO] [개별 저장소] 텍스트 파일 저장 완료: results/oss2025hnu_reposcore-py/score.txt
```
- 에러 예시 1: 존재하지 않는 사용자 정보 파일
```bash
$ python -m reposcore oss2025hnu/reposcore-py --user-info user_name.json --format text
[2025-04-22 10:14:11] [ERROR] ❌ 사용자 정보 파일을 찾을 수 없습니다.
```
- 에러 예시 2: 잘못된 …

사용자 정보 파일 유효성 검사 및 오류 메시지 추가

---

reposcore/__main__.py
reposcore/analyzer.py

#471
https://github.com/oss2025hnu/reposcore-py/commit/0c92a806f0d23028a4d5343b7304027d868da0e7
- `is_cache_update_required()` 함수를 구현하여 특정 조건에 따라 캐시를 업데이트해야 하는지 여부를 판단합니다.

feat: 캐시 업데이트 필요 여부 확인 함수 추가

---

reposcore/__main__.py

https://github.com/oss2025hnu/reposcore-py/issues/598
295cbf02533cc3da4dfd6a603177afdfc5031577
Optional 관련된 함수 코드 삭제 및 최신 python 타입 힌트 최신 코드로 수정했습니다.

[DOC] 코드의 type hints 중 Optional[T]대신 T | None 로 변경 에 대한 PR 

---

reposcore/__main__.py
reposcore/analyzer.py
reposcore/utils/retry_request.py

https://github.com/oss2025hnu/reposcore-py/issues/607 
c499973
1.  Optional 관련 함수 제거 및 코드 수정
2.  Dict 함수 제거, 모든 Dict 를 dict로 변경
3.  List를 list로 변경(typing 함수 제거)

코드의 type hints 중 List와 Optional을 최신 권장 형태로 수정 에 대한 PR 

---

docs/korean-timezone-guide.md

dbfced33aa06d94f1152b61acd3d66c55b53a71b
korean-timezone-guide.md 내의 오타를 수정하였습니다.

[DOC] 오타수정

---

docs/fork_sync_guide.md

#623 
a0f72681ef87aacc684ed88a54d4102410702852
포크한 저장소를 원본 저장소와 동기화 하는 방법을 추가
(CLI기반과 웹에서 동기화하는 방식을 추가)

[DOC] 포크 동기화 가이드 문서화

---

reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/630
0e83b2392388c2a0a0cf4dd0d88f5eaced5d3217
PR과 이슈 그래프가 따로 나오던 것을 하나로 합쳤습니다.

[REFACTOR] PR과 이슈 그래프를 하나로 통합 에 대한 PR

---

reposcore/analyzer.py
tests/test_analyzer.py

#625 
48aec88
- README.md에 명시된 점수 계산 공식에 맞게 `analyzer.py`의 점수 계산 로직을 수정했습니다.
- 실제 계산 결과에 맞게 `test_analyzer.py`의 test_user들의 기댓값을 수정했습니다.

README.md 기준으로 점수 계산 로직 수정

---

README.md
template_README.md

Issue ID
https://github.com/oss2025hnu/reposcore-py/issues/622
Specific Version
https://github.com/oss2025hnu/reposcore-py/commit/48aec88861c2cea1d7206b177ce0ad8a1c7af2ad
변경 내용
- README 템플릿(template_README.md)에 `docs/debug_guide.md` 링크를 추가하였습니다.
- 사용자들이 디버깅 및 로깅 가이드에 쉽게 접근할 수 있도록 개선하였습니다.

[DOC] 디버깅 및 로깅 가이드를 readme.md에 링크 연결 PR

---

README.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/639
750b7e62f542d77672c74951d655735c1e4ec446
README.md 내의 가이드 문서 카테고리별 정리와 간단한 설명을 적어두었습니다.

[DOC] README 내 가이드 문서 카테고리별 정리 제안

---

reposcore/__main__.py

#647 
a8779dc4b0f6a5c5cc21db9f46efc08ddc03d03d
이슈의 방향성이 개인 점수 출력 시에 CSV, TXT, 차트 이미지 등의 파일도 생성되지 않는 것으로 보여짐
그래서 --user 명령어로 실행 시, 개인 점수만 출력되게 수정함 (파일 생성 X)
전체 출력과 개인 출력 모두 정상 작동 확인함

[BUG] --user (유저명) 옵션을 사용하여 명령어 입력 시 다른 값도 같이 출력됨

---

docs/autoDocstring_guide.md

#563  
3bd402f8a32b7045d4474e437ced10ac61a4a44f
autoDocstring 확장 기능의 자동 설치 및 설정 내용을 반영하여 사용 가이드를 작성했습니다.
- 설치 방식 (자동/수동)
- 단축키 안내
- 스타일별 예시
- settings.json 실제 설정 반영
- 실제 프로젝트 설정 기준과 기본 예시 간의 차이 설명 포함
본 문서화 작업은 원래 autoDocstring 수동 사용 기준으로 계획된 이슈였으나,  
작업 시점 기준으로는 자동 설치 및 설정이 이미 적용된 상태이므로,  
최신 상태를 반영하여 내용을 정리했습니다.

[DOC] autoDocstring 사용법 및 설정 문서화

---

README.md
template_README.md

#657 
#611 (원래 있던 611 이슈도 해결)
3bd402f8a32b7045d4474e437ced10ac61a4a44f
README.md에 단일 / 통합 저장소 분석 방법과 분석 이후 생성된 겲과물 확인 방법을 추가함

[DOC] 저장소 분석 이후 결과물 확인 방법 문서화 요청

---

README.md

https://github.com/oss2025hnu/reposcore-py/issues/656
3bd402f8a32b7045d4474e437ced10ac61a4a44f
make README.md를 수행하여 PR요청하였습니다.

[BUG] README.md의 usage부분에 특정 옵션이 나타나지 않음

---

reposcore/__main__.py
reposcore/analyzer.py
reposcore/output_handler.py

66a57e47f1af157b656d934def90180cf3f52ad2
`__main__.py` 185번
`analyzer.py` 139 ~ 140번 
`output_handler` 129, 184, 187번 
들여쓰기 오타 수정

[STYLE] 들여쓰기 오타 수정

---

reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/670
66a57e47f1af157b656d934def90180cf3f52ad2
오른쪽 하단에 작게 표시되어있는 결과물 출력 시간을
제목 하단으로 위치 변경, 크기조정, 진한 색으로 변경

시간 출력 가독성 향상을 위한 위치 및 크기 조정

---

docs/cherry-pick_guide.md

https://github.com/oss2025hnu/reposcore-py/issues/672
4d6a6c3799f8ef1bd51afd5567bd949aed622840
Cherry-Pick 이용에 대한 내용 cherry-pick_guide.md 파일을 만들어 추가

Cherry-Pick 이용 문서화

---

reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/686 결과 출력 시 표 형식 복구 요청에 대한 PR입니다.
4d6a6c3799f8ef1bd51afd5567bd949aed622840
PrettyTable을 사용하여 txt파일의 표 형식을 복구하였습니다.

결과 출력 시 표 형식 복구 요청에 대한 PR

---

.devcontainer/devcontainer.json
.pylintrc
README.md
docs/pylint.md
requirements-dev.txt
template_README.md

[FEAT] Codespace환경에서 Pylint 확장을 자동설치 및 기본적인 설정 방법 문서 작성요청. https://github.com/oss2025hnu/reposcore-py/issues/596 에 대한 PR입니다.
13d9fbf0b4d1fcdcd72ed9bfb94814fa996ea30d
- pylint를 자동 설치할 수 있도록 requirements-dev.txt 및 devcontainer.json 수정
- pylint 설정을 통해 간단한 문법 오류만 잡을 수 있도록 추가
- pylint 사용법을 pylint.md로 추가하여 본문에 링크로 추가 (make readme)
- pylint 설정 파일 추가
다른 merge를 대기중인 커밋과 충돌된 것인지 ``git pull --no-rebase origin main``사용 후 다른 커밋 내용들이 추가됨. (41452fc, 이는 본인의 작업 내용이 아님)

pylint를 통한 문법 검사 기능 추가 및 사용 방법 문서화

---

.devcontainer/devcontainer.json

https://github.com/oss2025hnu/reposcore-py/issues/698
13d9fbf0b4d1fcdcd72ed9bfb94814fa996ea30d
해당 확장 프로그램을 devcontainer에 추가하여 자동으로 설치되게끔 추가
Live Server는 독립적으로 설치되며, HTML 파일이 없더라도 기존 코드에 영향을 주지 않습니다. 현재는 HTML 파일을 다른 팀원이 작업 중이므로, 실행은 그 이후에 가능합니다.

Live Server 확장 프로그램을 devcontainer에 추가

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/681
해당 PR과 연결된 이슈 ID를 작성해주세요.
빠르게 수정이 이루어지는 상황에서는, 기존에 제안된 내용이 이미 반영되었을 수 있으니 적용 대상 버전을 명확히 작성해주세요.
변경한 주요 내용들을 정리해주세요.

[BUG] 캐시 타임스탬프 키 불일치로 캐시가 항상 무효 처리됨

---

README.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/702
6c379f21d502ffbae2c25d09251c57bb576cd76f
template_README.md에 cherry-pick_guide.md로 이동하는 링크 추가하여 README.md에 반영

cherry-pick 이용 가이드 링크추가

---

reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/707
f41b3b17cc949ecf40dd8bcea6852434fb3ed601
chart, txt에 평균, 최고점, 최저점 추가

chart, txt에 평균, 최고점, 최저점 추가

---

reposcore/__main__.py

#727 
f41b3b17cc949ecf40dd8bcea6852434fb3ed601
/results/overall_repository에 txt파일도 표 형태로 출력하도록 바꿨습니다.

overall_repository 저장소별 기여도 txt파일도 표 형태로 출력 요청

---

README.md
docs/dependency_guide.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/732
ea166f569f40bac1874dcd66c3a20a0ba8c06c68
dependency_guide.md 파일 부족한 설명 추가

의존성 관리 가이드 설명 추가

---

.github/workflows/ci.yaml

Github action 워크플로우에 pylint 검사 추가 https://github.com/oss2025hnu/reposcore-py/issues/722 에 대한 PR입니다.
69fe5776314fa4d70e39f78a15b6e6b49cf9d14d
Github Action (CI)에 Pylint 검사 항목을 추가했습니다. 해당 검사는 ``.pylintrc``조건에 따라 진행됩니다.

pylint 검사항목 추가

---

reposcore/__main__.py
reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/684
https://github.com/oss2025hnu/reposcore-py/commit/69fe5776314fa4d70e39f78a15b6e6b49cf9d14d
--format all(또는 기본세팅) 실행시, index.html 생성
탭 기반 인터페이스
- 각 저장소별로 전환 가능한 탭
저장소별 정보
- 점수 테이블 (총점, 등급, 카테고리별 점수)
- 시각화된 차트
- CSV 다운로드 버튼
반응형 디자인
- 모바일 및 데스크톱 환경 모두에서 최적화된 레이아웃

[FEAT] --format all 옵션 시 통합 HTML 리포트 생성 기능 추가 PR

---

reposcore/analyzer.py
reposcore/output_handler.py

[해당 PR과 연결된 이슈 ID를 작성해주세요.
](https://github.com/oss2025hnu/reposcore-py/issues/744)
0d431ab788138bbb576288bd1b271d8837ddff7a
기존에는 동점자임에도 다른 순위가 적용되었습니다.
analyzer.py 에서 total점수를 기준으로 공동 등수를 계산하는 _finalize_scores() 함수를 추가했습니다.
이것만으론 결과물에 수정한 부분이 반영되지 않아
output_handler.py 의 csv, text, chart, html테이블 출력 코드를 수정했습니다.
현재 739 이슈가 진행되지 않아 테스트가 정상 작동하지 않습니다. 임시방편으로 수정하고 테스트 시행 결과 아래와 같습니다.
변경전 
|  17  |     sun-juu      |     17.0    |   F   |        6.0       |     4.0   |     0.0    |          6.0        |      1.0     |
|  18  |     xhltkwk      |     17.0    |   F   |        9.0       |     2.0   |     0.0    |          4.0        |      2.0     |
|  19  |  moongyeong000   |     15.0    |   F   |       12.0       |     2.0   |     0.0    |          0.0        |      1.0     |
|  20  | …

[BUG] 동점자 순위처리 안 됨 #744 에 대한 pr입니다.

---

README.md
template_README.md

https://github.com/oss2025hnu/reposcore-py/issues/802
57d655e63166bc6be1cb9f303777b73994f59d7b
중복되는 socre.csv, score.txt, chart.png에 대한 설명을 수정했습니다.

[DOC] README에서 중복된 결과 파일 설명 정리 에 대한 pr입니다.

---

reposcore/__main__.py
reposcore/output_handler.py

https://github.com/oss2025hnu/reposcore-py/issues/808
5b627b379cfc71abb2bf122a0af8750387cc640a
파일 이름 수정과 폴더가 합쳐짐에 따라 경로 재설정을 진행하였고 csv가 format html 할때도 나오게 바꿔서 csv가 생성될 수 있게금 바꿨습니다.

html의 csv 파일 오류 해결

---

reposcore/__main__.py
reposcore/analyzer.py
reposcore/common_utils.py
reposcore/github_utils.py
reposcore/output_handler.py

#646
f6007c94046c0235743c55c49e6f56e6593d81e3
- verbose옵션과 같이 동작하는 logger 개선
- `common_utils.py`에서 log 함수 제거

verbose옵션과 같이 동작하는 logger 개선

---

reposcore/analyzer.py

https://github.com/oss2025hnu/reposcore-py/issues/821
4665d2d59387dae759a2253bc831e4c2e2713750
-수정 전 :
$ python -m reposcore oss2025hnu/reposcore-py oss2025hnu/reposcore-js oss2025hnu/reposcore-cs --format all
[2025-06-13 00:50:39] [INFO] 저장소 분석 시작: oss2025hnu/reposcore-py, oss2025hnu/reposcore-js, oss2025hnu/reposcore-cs
저장소 분석 진행:   0%|                                                                                                                                                                                       | 0/3 [00:00<?, ?it/s][2025-06-13 00:54:45] [INFO] oss2025hnu/reposcore-py 분석 결과(CSV, TXT, Chart) 저장 완료: results/oss2025hnu_reposcore-py
저장소 분석 진행:  33%|██████████████████████████████████████████████████████████ …

[BUG] PR 병합 여부 확인 방식으로 인한 분석 속도 저하 문제 에 대한 pr입니다.
